'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "rust/src/**/*.rs"

# Include required specifications here
[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc5246" # The Transport Layer Security (TLS) Protocol Version 1.2

[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc5869" # HMAC-based Extract-and-Expand Key Derivation Function (HKDF)

[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc8446" # The Transport Layer Security (TLS) Protocol Version 1.3

[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc8448" # Example Handshake Traces for TLS 1.3

[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc7627" # Transport Layer Security (TLS) Session Hash and Extended Master Secret Extension

[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc5746" # Transport Layer Security (TLS) Renegotiation Indication Extension

[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc4492" # Elliptic Curve Cryptography (ECC) Cipher Suites for Transport Layer Security (TLS)

[[specification]]
source = "https://www.rfc-editor.org/rfc/rfc8422" # Elliptic Curve Cryptography (ECC) Cipher Suites for Transport Layer Security (TLS) Versions 1.2 and Earlier
[report.html]
enabled = true
path = "rust/tests/compliance/report.html"

# Enable snapshots to prevent requirement coverage regressions
[report.snapshot]
enabled = true
